
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install
script:
  - python tests/suite.py
after_success:
  - coverage run tests/suite.py
  - codecov
